# Generated by Django 3.1.4 on 2020-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(default=21, max_length=254),
            preserve_default=False,
        ),
    ]
