# Generated by Django 3.1.4 on 2020-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description_product',
            new_name='about_product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='details_product',
            new_name='more_details',
        ),
        migrations.AddField(
            model_name='products',
            name='colour',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='model_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
