# Generated by Django 3.1.4 on 2020-12-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='post_image')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('desc_min', models.TextField()),
                ('created_by', models.CharField(max_length=50)),
                ('resources', models.CharField(max_length=100)),
            ],
        ),
    ]
