# Generated by Django 3.1.4 on 2020-12-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedBlogProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_blog_product', models.ImageField(upload_to='image_blog_products')),
                ('brand_blog_product', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('link_product_amazon', models.URLField()),
                ('blog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog')),
            ],
        ),
    ]
