# Generated by Django 3.1.4 on 2020-12-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_relatedblogproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedblogproducts',
            name='blog_product',
        ),
        migrations.AddField(
            model_name='relatedblogproducts',
            name='blog_product',
            field=models.ManyToManyField(to='blog_app.Blog'),
        ),
    ]
