# Generated by Django 3.1.4 on 2020-12-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog_app', '0005_auto_20201228_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
