# Generated by Django 3.1.4 on 2020-12-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedblogproducts',
            name='blog_rel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_rel', to='blog_app.blog'),
            preserve_default=False,
        ),
    ]
