# Generated by Django 3.1.4 on 2020-12-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_comment_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
